# Generated by Django 5.0.4 on 2024-04-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemodel",
            name="EmployeePanNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
